chapter/src/main/java/cn/mnmcloud/model/Customer.java
package cn.mnmcloud.model;

/**
 *
 * @author max
 * @date 2018/7/9
 * Customer
 */
public class Customer {
    /**
     * ID
     */
    private  long id;

    /**
     * name
     */
    private  String name;

    /**
     * contract
     */
    private String contract;

    /**
     * Phone
     */
    private String telephone;

    /**
     * Email
     */
    private String email;

    /**
     * remark
     */
    private String remark;

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getContact() {
        return contract;
    }

    public void setContact(String contract) {
        this.contract = contract;
    }

    public String getTelephone() {
        return telephone;
    }

    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

}

chapter/src/main/java/cn/mnmcloud/controller/CustomerCreateServlet.java
package cn.mnmcloud.controller;


import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;

/**
 *
 * @author max
 * @date 2018/7/10
 */
@WebServlet("/customer_create")
public class CustomerCreateServlet extends HttpServlet {
    /**
     * Entry create customer UI
     * @param req
     * @param resp
     * @throws ServletException
     * @throws IOException
     */
    @Override
    protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
        //TODO
        super.doGet(req, resp);
    }

    /**
     * create customer
     * @param req
     * @param resp
     * @throws ServletException
     * @throws IOException
     */
    @Override
    protected void doPost(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
        //TODO
        super.doPost(req, resp);
    }
}

chapter/src/main/java/cn/mnmcloud/controller/CustomerServlet.java
package cn.mnmcloud.controller;

import cn.mnmcloud.model.Customer;
import cn.mnmcloud.service.CustomerService;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.util.List;

/**
 *
 * @author max
 * @date 2018/7/15
 */
@WebServlet("/customer")
public class CustomerServlet extends HttpServlet{
    private CustomerService customerService;
    @Override
    protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
        List<Customer> customerList = customerService.getCustomerList();
        req.setAttribute("customerList", customerList);
        req.getRequestDispatcher("/WEB-INF/view/customer.jsp").forward(req,resp);
    }

    @Override
    public void init() throws ServletException {
        customerService = new CustomerService();
    }
}

chapter/src/main/webapp/WEB-INF/view/customer.jsp
<%--
  Created by IntelliJ IDEA.
  User: max
  Date: 2018/7/15
  Time: 下午10:40
  To change this template use File | Settings | File Templates.
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ page pageEncoding="UTF-8" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<c:set var="BASE" value="${pageContext.request.contextPath}"/>
<html>
<head>
    <title>客户管理</title>
</head>
<body>
<table>
    <thead>
    <tr>
        <th>客户名称</th>
        <th>联系人</th>
        <th>电话号码</th>
        <th>邮箱地址</th>
        <th>操作</th>
    </tr>
    </thead>
    <tbody>
    <c:forEach var="customer" items="${customerList}">
        <tr>
            <td>${customer.name}</td>
            <td>${customer.contact}</td>
            <td>${customer.telephone}</td>
            <td>${customer.email}</td>
            <td>
                <a href="${BASE}/customer_edit?id=${customer.id}">Edit</a>
            </td>
            <td>
                <a href="${BASE}/customer_delete?id=${customer.id}">Delete</a>
            </td>
        </tr>
    </c:forEach>
    </tbody>
</table>
</body>
</html>

chapter/src/main/webapp/WEB-INF/view/cutomer_create.jsp
<%@ page pageEncoding="utf-8" %>
<html>
<head>
    <title>
        客户管理 - 创建客户
    </title>
</head>
<body>
<h1>创建客户界面</h1>
<%--TODO--%>
</body>
</html>